# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_postmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostModel',
        ),
        migrations.AlterField(
            model_name='sessiontoken',
            name='session_token',
            field=models.CharField(max_length=15),
        ),
    ]
