# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20170801_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='has_liked',
            field=models.BooleanField(default=False),
        ),
    ]
