# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_upvotingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='upvotingmodel',
            name='upvote_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='caption',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
