# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20170817_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvotingmodel',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='upvotingmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='upvote_number',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='UpvotingModel',
        ),
    ]
